"""empty message

Revision ID: 14739f746960
Revises: add_total_amount_to_sale
Create Date: 2025-04-04 12:14:32.208768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14739f746960'
down_revision = 'add_total_amount_to_sale'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
