"""add total_amount to sale

Revision ID: add_total_amount_to_sale
Revises: bd61a6daff09
Create Date: 2025-03-31 01:47:02.526689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_total_amount_to_sale'
down_revision = 'bd61a6daff09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###
    
    # Atualiza os valores existentes
    from sqlalchemy import text
    op.execute(
        text(
            "UPDATE sale SET total_amount = total_financed WHERE is_financed = 1; "
            "UPDATE sale SET total_amount = total_price WHERE is_financed = 0 OR total_amount IS NULL;"
        )
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###