"""add financing fields to sale model

Revision ID: bd61a6daff09
Revises: 
Create Date: 2025-03-31 00:47:02.526689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd61a6daff09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_financed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('financing_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_financed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_payment', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('monthly_payment')
        batch_op.drop_column('total_financed')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('financing_years')
        batch_op.drop_column('is_financed')

    # ### end Alembic commands ###
